---
title: "How to create the cohort sequence"
author: Xihang Chen, Tyman Stanford, Berta Raventós, Nicole Pratt, Ed Burn, Marti Catala, Danielle Newby, Nuria Mercade-Besora, Mike Du, Yuchen Guo, Kim Lopez, Marta Alcalde-Herraiz
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How to create the cohort sequence}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: 72
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Introduction
In this vignette we will introduce the functionalities of `getCohortSequence()` function. First of all, we will use `mockPatientProfiles()` from PatientProfiles package to create a mock database. This **cdm** reference already contains two mock cohorts that we will use for the following examples. 

```{r setup}
library(CohortSymmetry)
library(dplyr)
library(PatientProfiles)

cdm <- mockPatientProfiles()
cdm
```


```{r}
library(PatientProfiles)
cdm <- mockPatientProfiles()
cdm <- CohortSymmetry::getCohortSequence(
  cdm = cdm,
  indexTable = "cohort1",
  markerTable = "cohort2"
)



````


